######################################################################
# Automatically generated by qmake (2.01a) Sun Sep 22 17:02:49 2013
######################################################################

TEMPLATE = app
TARGET = 
DEPENDPATH += .
INCLUDEPATH += .

# Input
HEADERS += ledtest.h
FORMS += ledtest.ui
SOURCES += ledtest.cpp main.cpp
